##################################################
#
# Run the application to install a Magento on each new branch
#
##################################################

name: Continuous testing

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      MAGENTO_DIRECTORY: ./tmp/magento

    steps:
      - uses: actions/checkout@v2

      - name: Install system requirements
        run: |
          wget -qO- "https://github.com/havoc-io/mutagen/releases/download/$MUTAGEN_VERSION/mutagen_linux_amd64_$MUTAGEN_VERSION.tar.gz" | sudo tar xvz -C "/usr/local/bin/"
          mutagen daemon start
          sudo ln -s "$PWD/bin/console" "/usr/local/bin/magephi"
        env:
          MUTAGEN_VERSION: v0.11.2

      - name: Cache Magephi dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Cache Magento dependencies
        uses: actions/cache@v1
        with:
          path: ${{env.MAGENTO_DIRECTORY}}/vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

      - name: Initialize Magento 2 project directory
        run: mkdir -p ${{env.MAGENTO_DIRECTORY}}

      - name: Create a Magento Open Source project
        run: composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition ${{env.MAGENTO_DIRECTORY}} --ignore-platform-reqs --no-progress --no-dev --no-install
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}

      - name: Install the Docker environment through Composer
        run: composer require emakinafr/docker-magento2 --dev --no-progress --ignore-platform-reqs
        working-directory: ${{env.MAGENTO_DIRECTORY}}
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}

      - name: Install Magento
        run: sudo magephi install --no-interaction
        working-directory: ${{env.MAGENTO_DIRECTORY}}
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}

      - name: Check status
        run: magephi status
        working-directory: ${{env.MAGENTO_DIRECTORY}}

      - name: Try accessing the setup page
        run: curl --insecure --location --resolve "www.magento.localhost:443:127.0.0.1" https://www.magento.localhost/setup/

      - name: Uninstall project
        run: yes | magephi uninstall -v
        working-directory: ${{env.MAGENTO_DIRECTORY}}