name: Tests Integration

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --verbose --dry-run

      - name: PHPStan
        run: make phpstan

      - name: Security
        run: |
          make security
          yarn audit